package enums;

public enum CategoriaLivro {
	ARTE, AJUDA, BIOGRAFIA, EXATAS, EDUCAÇÃO, HUMANAS, COMIDAS, DIREITO, HISTORIA, ESTRANGEIRO, INFANTIL, 
	NACIONAL, NEGOCIOS, HQ, SAUDE, TECNOLOGIA, TURISMO, TUDO
}
